name: Frida Windows Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Architecture to build'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86
          - x86_64

jobs:
  build-frida:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ inputs.architecture == 'x86_64' && 'x64' || inputs.architecture }}
          
      - name: Install dependencies
        run: |
          pip install setuptools toml
      
      - name: Check out releng
        run: |
          git submodule update --init --depth 1 releng
          cd releng
          git submodule update --init --depth 1
      
      - name: Add environment variables
        run: |
          echo "FRIDA_PREFIX=$env:RUNNER_WORKSPACE\dist" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "FRIDA_VERSION=$(python ${{ github.workspace }}/releng/frida_version.py)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Grab needed submodules
        run: python tools/ensure-submodules.py frida-core
      
      - name: Install Qt if needed
        if: ${{ inputs.architecture == 'x86_64' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          setup-python: false
      
      - name: Download toolchain
        run: |
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\deps" -Force
          python releng/deps.py sync toolchain windows-${{ inputs.architecture }} "$env:GITHUB_WORKSPACE\deps\toolchain-windows-${{ inputs.architecture == 'x86_64' && 'x86_64' || 'x86' }}"
      
      - name: Download SDK
        run: |
          python releng/deps.py sync sdk windows-${{ inputs.architecture }} "$env:GITHUB_WORKSPACE\deps\sdk-windows-${{ inputs.architecture }}"
      
      - name: Setup build environment
        run: |
          $Location = "$env:GITHUB_WORKSPACE\build"
          New-Item -ItemType Directory -Path "$Location" -Force
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\build\sdk-windows-${{ inputs.architecture }}" -Force
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\build\toolchain-windows-${{ inputs.architecture }}" -Force
          
          # Copy SDK files
          $SdkSource = "$env:GITHUB_WORKSPACE\deps\sdk-windows-${{ inputs.architecture }}"
          if (Test-Path $SdkSource) {
            Copy-Item -Recurse -Force "$SdkSource\*" "$env:GITHUB_WORKSPACE\build\sdk-windows-${{ inputs.architecture }}\"
          }
          
          # Copy toolchain files
          $ToolchainSource = "$env:GITHUB_WORKSPACE\deps\toolchain-windows-${{ inputs.architecture == 'x86_64' && 'x86_64' || 'x86' }}"
          if (Test-Path $ToolchainSource) {
            Copy-Item -Recurse -Force "$ToolchainSource\*" "$env:GITHUB_WORKSPACE\build\toolchain-windows-${{ inputs.architecture }}\"
          }

      - name: Configure
        run: >-
          .\configure
          --prefix=$Env:FRIDA_PREFIX
          --host=windows-${{ inputs.architecture }}
          --enable-gadget
          --enable-server
          --enable-portal
          --enable-inject
          --
          "-Dfrida_qml=auto"
          "-Dfrida-gum:devkits=gum,gumjs"
          "-Dfrida-core:devkits=core"
      
      - name: Compile
        run: .\make
      
      - name: Install
        run: .\make install
      
      - name: List detailed build products
        run: |
          echo "Build completed successfully!"
          echo "--------------------------------------"
          echo "Build products are available at: $Env:FRIDA_PREFIX"
          echo ""
          echo "frida-server: $Env:FRIDA_PREFIX\bin\frida-server.exe"
          echo "frida-portal: $Env:FRIDA_PREFIX\bin\frida-portal.exe"
          echo "frida-inject: $Env:FRIDA_PREFIX\bin\frida-inject.exe"
          if ('${{ inputs.architecture }}' -eq 'x86') {
            echo "frida-gadget: $Env:FRIDA_PREFIX\lib\frida\32\frida-gadget.dll"
          } else {
            echo "frida-gadget: $Env:FRIDA_PREFIX\lib\frida\64\frida-gadget.dll"
          }
          echo ""
          echo "Devkits:"
          echo "- Gum: $Env:FRIDA_PREFIX\lib\frida\devkits\gum\"
          echo "- GumJS: $Env:FRIDA_PREFIX\lib\frida\devkits\gumjs\"
          echo "- Core: $Env:FRIDA_PREFIX\lib\frida\devkits\core\"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-${{ inputs.architecture }}
          path: ${{ env.FRIDA_PREFIX }}
