name: Windows Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Architecture to build'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86
          - x86_64

jobs:
  build-frida:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ inputs.architecture == 'x86_64' && 'x64' || inputs.architecture }}
          
      - name: Install setuptools
        run: pip install setuptools
        
      - name: Check out releng
        run: |
          git submodule update --init --depth 1 releng
          cd releng
          git submodule update --init --depth 1
          
      - name: Add convenience environment variables
        run: |
          echo "FRIDA_PREFIX=$Env:RUNNER_WORKSPACE\dist" >> $Env:GITHUB_ENV
          echo "FRIDA_VERSION=$(python ${{ github.workspace }}/releng/frida_version.py)" >> $Env:GITHUB_ENV
          
      - name: Grab needed submodules
        run: python tools/ensure-submodules.py frida-core
        
      - name: Build dependencies using releng scripts
        run: |
          python releng\deps.py roll toolchain windows-${{ inputs.architecture }}
          python releng\deps.py roll sdk windows-${{ inputs.architecture }} --activate
        
      - name: Configure
        run: >-
          .\configure
          --prefix=$Env:FRIDA_PREFIX
          --host=windows-${{ inputs.architecture }}
          --enable-gadget
          --enable-server
          --enable-portal
          --enable-inject
          --
          "-Dfrida_qml=auto"
          "-Dfrida-gum:devkits=gum,gumjs"
          "-Dfrida-core:devkits=core"
          
      - name: Compile
        run: .\make
        
      - name: Install
        run: .\make install
        
      - name: List detailed build products
        run: |
          echo "Build completed successfully!"
          echo "--------------------------------------"
          echo "Build products are available at: $Env:FRIDA_PREFIX"
          echo ""
          echo "frida-server: $Env:FRIDA_PREFIX\bin\frida-server.exe"
          echo "frida-portal: $Env:FRIDA_PREFIX\bin\frida-portal.exe"
          echo "frida-inject: $Env:FRIDA_PREFIX\bin\frida-inject.exe"
          if ('${{ inputs.architecture }}' -eq 'x86') {
            echo "frida-gadget: $Env:FRIDA_PREFIX\lib\frida\32\frida-gadget.dll"
          } else {
            echo "frida-gadget: $Env:FRIDA_PREFIX\lib\frida\64\frida-gadget.dll"
          }
          echo ""
          echo "Devkits:"
          echo "- Gum: $Env:FRIDA_PREFIX\lib\frida\devkits\gum\"
          echo "- GumJS: $Env:FRIDA_PREFIX\lib\frida\devkits\gumjs\"
          echo "- Core: $Env:FRIDA_PREFIX\lib\frida\devkits\core\"
