name: Windows Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Architecture to build'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86
          - x86_64

jobs:
  sdk-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          

      - name: Check out releng
        run: |
          git submodule update --init --depth 1 releng
          cd releng
          git submodule update --init --depth 1
          
      - name: Add convenience environment variables
        run: |
          echo "FRIDA_PREFIX=$Env:RUNNER_WORKSPACE\dist" >> $Env:GITHUB_ENV
          echo "FRIDA_VERSION=$(python releng/frida_version.py)" >> $Env:GITHUB_ENV
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ inputs.architecture == 'x86_64' && 'x64' || inputs.architecture }}
          
      - name: Install setuptools
        run: pip install setuptools
        
      - name: Cache SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: |
            build/sdk-windows-${{ inputs.architecture }}
            build/toolchain-windows-${{ inputs.architecture }}
          key: ${{ runner.os }}-sdk-windows-${{ inputs.architecture }}-${{ hashFiles('releng/setup-env.sh', 'releng/windows-*') }}
          
      - name: Build SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: .\make deps

  frida-windows:
    needs: sdk-windows
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          

      - name: Check out releng
        run: |
          git submodule update --init --depth 1 releng
          cd releng
          git submodule update --init --depth 1
          
      - name: Add convenience environment variables
        run: |
          echo "FRIDA_PREFIX=$Env:RUNNER_WORKSPACE\dist" >> $Env:GITHUB_ENV
          echo "FRIDA_VERSION=$(python releng/frida_version.py)" >> $Env:GITHUB_ENV
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ inputs.architecture == 'x86_64' && 'x64' || inputs.architecture }}
          
      - name: Install setuptools
        run: pip install setuptools
        
      - name: Install Qt
        if: ${{ contains(inputs.architecture, '64') }}
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          cache: true
          setup-python: false
          
      - name: Restore SDK from cache
        uses: actions/cache@v3
        with:
          path: |
            build/sdk-windows-${{ inputs.architecture }}
            build/toolchain-windows-${{ inputs.architecture }}
          key: ${{ runner.os }}-sdk-windows-${{ inputs.architecture }}-${{ hashFiles('releng/setup-env.sh', 'releng/windows-*') }}
          
      - name: Configure
        run: >-
          .\configure
          --prefix=$Env:FRIDA_PREFIX
          --host=windows-${{ inputs.architecture }}
          --enable-gadget
          --enable-server
          --enable-portal
          --enable-inject
          --
          "-Dfrida_qml=auto"
          "-Dfrida-gum:devkits=gum,gumjs"
          "-Dfrida-core:devkits=core"
          
      - name: Compile
        run: .\make
        
      - name: Install
        run: .\make install
        
      - name: List build products
        run: |
          echo "Build completed successfully!"
          echo "--------------------------------------"
          echo "Build products are available at: $Env:FRIDA_PREFIX"
          echo "You can find the following components:"
          echo "- frida-server.exe"
          echo "- frida-portal.exe"
          echo "- frida-inject.exe"
          if ('${{ inputs.architecture }}' -eq 'x86') {
            echo "- frida-gadget.dll (32-bit)"
          } else {
            echo "- frida-gadget.dll (64-bit)"
          }
          echo "--------------------------------------"
